services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - rede_workshop

  workshop:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: workshop-service
    environment:
      - POSTGRES_DB=postgres
      - PORT=5432
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - rede_workshop

networks:
  rede_workshop:
    driver: bridge